<h2>MODEL DEPLOYMENT</h2>

By the end of this module the learner should be able to:
1. Define model deployment.
2. Distinguish between the different deployment models.
3. Identify the various deployment environments.
4. Create a web app using streamlit.
5. Create a model
6. Integrate a model into an application.

<h2>Definition of model deployment</h2>

Lets us start by thinking about what model deployment is all about. When we create the models in our jupyter notebooks or R environment, we are not able to share this with the people who want to constantily use them for the machine learning tasks such as predictions, classification and so on. We therefore need to make our models accessible for the actual users to be able to use them. This process of availing our models to potential users is what is reffered to us **model deployment**.

Deploying a  model will involve integrating it with existing applications. For example if you were building a machine learning model to help doctors diagnosize patients with diabetics, you will need to integrate it with the existing health management system used in the hospital or you will need to develop an application that will help the doctor put the patients sysmptoms and then this information is sent to the model through an API (Intergreted application interface). The model then serves the request and sends the prediction to the doctor.

As much as model deployment is the last stage in the machine learning cycle, model deployment is the first step in what is reffered to us model management.

A typical cycle for machine learning model management is shown in the diagram below;


The first step  involves the deployment of the model. Once the model is deployed, its performance is monitored. If the performance of the model reduces to a cerain level, the model will require retraining and evaluation and so that the old model can be replaced with a new model.

<h3>Why deploy the models</h3>

- Model deployment is the final step in the machine learning pipeline, where the model transitions from a development/testing phase to real-world usage.
- Deployed models enable organizations to automate decision-making processes, optimize workflows, and derive actionable insights from data.
- Efficient deployment ensures that the benefits of machine learning models are realized in practical applications, leading to improved efficiency, accuracy, and competitiveness.

<h2>Machine learning model deployment models</h2>

In general, there are 3 ways you can deploy our trained machine learning model.

1. one off
The one off model is applicable in cases where the model is only required at one particular time. This is appliable if the model is required for a temporary task. This can be applicable in a scenerio where for example if the governemnt is rolling out vaccination lets say for measals, they can develop a model for predicting the people at high risk for priotizing the distribution of the vaccine.

2. Batch
The batch model allows you to have an updated version of the model at all times. This is useful in cases where you do not need predictions done on real time data. The model gets trained on the whole dataset at certain period and used for prediction. An applicable area can be in disease servillance where the data is collected periodically like monthly and used in training the model.
3. Realtime

Realtime deployment is applicable where predictions are needed in realtime. Realtime deployment of the machine learning model can be applicable in cases such as disease servillance in case of pandemics where you might want to know everytime where new cases are reported.

<h2>Factors to consider when choosing a model deployment model</h2>

- How frequent/often are the predictions required and how urgent the results are required

- Do we need individualpredictions or batch predictions

- Cost of deploying the model
- Computing capabilities required by the model
- The complexity of the model. Realtime deployment model requires less complex models

<h2>Challenges in machine learning model deployment</h2>

- The discrepancies in programming langauges: As you have noted by now machine learning models mostily using R or Python but most applications that the model need to be integreated into are written in other langauges such as Java, PhP, type script, Ruby, C#. The integration of the models to this applications may pose a challenge.

- Model drift: When the performance of a machine learning model degrades to a level that is below the benchmark, it is reffered to us model drift. Depending on the use of the model, the degradation of the model performance can cause a major impact expecially in the medical field. It is therefore very important to be able to monitor the performance of machine learning models so that any degradation in performance can be captured at an early stage. Model degradation can be caused by:

1. Changing data behavior: In a typical machine learning model creation, the model is trained using historical data which is in a particular format but we know data data can change and the machine learning model will be exposed with data it has not seen before hence the poor performance. For example if a machine learning was trained to identify wheather someone had covid-19 using the data collected in 2019 which had various symptoms. At the beginning the machine learning model will perform well when patients present with the same symptoms the model was trained for. But over time when new variants of Covid-19 with different symptoms arise, the model may fail to identify if a person has Covid-19 based on the new symptoms. In such cases when there is a degredation of the performance of the model, is important to train the model on the emwrging data  or new data.

2. Changing interpretation of the new data (Concept drift): Concept drift happens when the clasification of an outcome variable changes in meaning. For example if previous target variable for the machine learning model for covid during the early stages was either someone had covid or not. But with the emergence of the new variants more outcome variable are available. Instead of just wanting to know if someone has covid or not, one will be interested to find the covid variant that soemone is suffering from based on the symptoms. With such change it is important to retrain the model with the new knowledge.

3. Deploying the model on the cloud or on premise: Just like the discussion on whether to adopt cloud compputing or deploy applications on premise, the decisons of where the model will be hosted has trendoffs to be made. The issues of security, privacy and accessibility will suffice.
4. Model monitoring: It is important to have model monitorin plan. This will help in being able to determine the threshold of the model performance. If there is no plan, there is a danger of failing to monitor the performance of the model.

5. Vesrion control: With the fact that the machine learning model will need to be retrained, it is important to keep tab of the versions of the model so that in case of anything you can always go back to the previous working version. One of the most common used version control tools is called Github.


<h2>Deployment environments</h2>

1. streamlit
2. Heroku
3. TensorFlow Serving with Docker
4. AWS
5. Microsoft Azure

These are just a few places where you can deploy your machine learning model. You can explore more deployment environments.

<h2>Steps for deploying a machine learning model</h2>

1. Training of the model
2. Saving the model
3. Select the deployment environment
4. Set up the requirements: These are dependancies that the model depends on such as all the libraries that were imported.
5. Serve the model using REST API such as flask, Django, FastAPI or streamlit
6. Deploy the model in the selected environment such as heroku server, AWS e.tc.
7. Create the interface to access the model such as a webform

Lets go through the process listed above using an example for predicting the probablity that someone has cholera or not?

<h2>Machine learning deployment as a web service</h2>

As we have already learnt, we mainly test and train our machine learning models using Google Colab/jupyter notebook but if we require to conect our model to an app or web service, we will need to deploy it as a webserver. This server can either be in the cloud or on premise. In this section, we are going to explore how to deploy our model Using streamlit.

** Introduction to Streamlit**

Streamlit is an easy to use open-source Python library used to create and share custom web apps for machine learning and data science projects. It allows you to turn your trained models into shareable web apps in minutes, without needing extensive web development skills.

A web application, is an application that you can access using the browser

Before we use streamlit to deploy our model, we will need to first of all install it. To install it, we will use pip which you were introduced to in the first chapter. The code to install streamlit is as follows

    pip install streamlit
If you already have it in the machine, you will get the message "requirements satisified"

Let's start by learning a few commands that you can use in streamlit by creating the hello world web app.

In [ ]:
!pip install streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 45.8 MB/s eta 0:00:00


Before we start using streamlit, we have to import it. We will import it with an alias st the same way we were importing pandas with the alias pd as follows

**Code explanation**

The **st. title** method helps to write a title for our application

The **st.write"** is used to write any thing to the screen

The **st.slider** will create a slider for you that you can be able to drag through.

To see how our app is working, we will transfer the code above to a text editor and save it as **app.py** then we will use the streamlit run command to run our file from the command prompt.


**<h2>CREATING OUR MODEL</h2>**

Now that we know the basic streamlit, lets create the model we will deploy using the stramlit app.

**<h4>Importing the libraries</h4>**

In [ ]:
#import pandas as pd
#import numpy as np
#from sklearn.linear_model import LinearRegression
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#import matplotlib.pyplot as plt


In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Next we load the dataset for cholera

In [ ]:
data=pd.read_excel("/content/drive/MyDrive/engage2/Datasets/Cholera outbreak dataset.xlsx")

Lets look at how the data is by using the head function

In [ ]:
data.head()

,Test_result,Test_date,Sex,Age,Subcounty,Water,Sanitation,Income,Informal_settlement,Outcome
0,0,2023-05-12,2,15,4,1,3,3,2,0
1,1,2023-05-13,2,6,2,3,3,1,1,0
2,0,2023-05-14,2,9,3,2,2,5,2,0
3,0,2023-05-15,2,10,1,4,4,5,2,0
4,0,2023-05-16,1,10,2,2,4,1,1,0


In [ ]:
missing_data=data.isnull().sum()
print(missing_data)

Test_result            0
Test_date              0
Sex                    0
Age                    0
Subcounty              0
Water                  0
Sanitation             0
Income                 0
Informal_settlement    0
Outcome                0
dtype: int64


In [ ]:
data.columns


Index(['Test_result', 'Test_date', 'Sex', 'Age', 'Subcounty', 'Water',
       'Sanitation', 'Income', 'Informal_settlement', 'Outcome'],
      dtype='object')

In [ ]:
data["Test_result"].unique()

array([0, 1])

In [ ]:
data["Sex"].unique()

array([2, 1])

In [ ]:
data["Water"].unique()

array([1, 3, 2, 4])

In [ ]:
data["Subcounty"].unique()

array([4, 2, 3, 1, 6, 5])

In [ ]:
data["Sanitation"].unique()

array([3, 2, 4, 1])

In [ ]:
data["Income"].unique()

array([3, 1, 5, 4, 2])

In [ ]:
data["Informal_settlement"].unique()

array([2, 1])

In [ ]:
data["Outcome"].unique()

array([0, 1])

In [ ]:
data.shape

(312, 10)

In [ ]:
#Create an X and y values
#X=data[["age","height"]]
#X=data["Age (months)"]
#y=data["weight"]

X = data.drop(columns=["Test_date","Outcome"])
y = data["Outcome"]

X=X.to_numpy()
#X=X.to_numpy().reshape(-1, 1)
y=y.to_numpy()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#y_pred=model.predict(X_test)

In [ ]:
# finding out the accuracy
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred=model.predict(X_test)
# Use appropriate metrics for classification problems
score = accuracy_score(y_test, y_pred.round()) # Round predictions for accuracy score in classification
print("Accuracy:", score)

# You can also use other classification metrics like confusion matrix and classification report
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred.round()))
print("Classification Report:\n", classification_report(y_test, y_pred.round()))

Accuracy: 0.9361702127659575
Confusion Matrix:
 [[88  0]
 [ 6  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        88
           1       0.00      0.00      0.00         6

    accuracy                           0.94        94
   macro avg       0.47      0.50      0.48        94
weighted avg       0.88      0.94      0.91        94



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# finding out the accuracy
#from sklearn.metrics import mean_squared_error, r2_score - meant for Linear regression

# Use appropriate metrics for regression problems
# mse = mean_squared_error(y_test, y_pred)
# r2 = r2_score(y_test, y_pred)

# print("Mean Squared Error:", mse)
# print("R-squared:", r2)

Once we trained our model and we are satisfied with the output, we will save our model using joblib

In [ ]:
#Testing the Logistic Model
print(model.predict([[0,2,56,3,4,2,5,2]]))

[0]


In [ ]:
# Mount Google Drive
#from google.colab import drive
#drive.mount('/content/drive')

# Check if the directory exists, if not create it
import os
directory_path = "/content/drive/My Drive/engage2/Cholera" # Changed directory name
if not os.path.exists(directory_path):
    os.makedirs(directory_path)

# Now try saving the model again
import joblib
joblib_file = "/content/drive/My Drive/engage2/Cholera/cholera_model.joblib" # Changed filename
joblib.dump(model, joblib_file)

['/content/drive/My Drive/engage2/Cholera/cholera_model.joblib']

In [ ]:
data.columns

Index(['Test_result', 'Test_date', 'Sex', 'Age', 'Subcounty', 'Water',
       'Sanitation', 'Income', 'Informal_settlement', 'Outcome'],
      dtype='object')

Once the model is saved we can now create a simple app which we can use to serve our model. We can create the app using streamlit as follows

In [ ]:
# Importing the necessary libraries
import streamlit as st
import joblib
import numpy as np

# Loading your saved model. Be sure to change the path if needed
model = joblib.load("/content/drive/MyDrive/engage2/Cholera/cholera_model.joblib") # Changed path

st.title('Cholera Prediction App') # Changed title
st.write("This app predicts the probability of someone having cholera based on their age and test result.") # Changed description

# Input fields
#test_result = st.selectbox('Test_result', ['0', '1'])
test_result = st.selectbox('Test_result', options=[0, 1], index=0)
#sex = st.selectbox('Sex', options=[0, 1], index=0)
#sex= st.selectbox('Sex', ['1', '2'])
sex= st.selectbox('Sex', options=[1, 2], index=1)
age= st.number_input('Age', min_value=0, max_value=100, value=20) # Changed min/max to integer
#subcounty= st.selectbox('Subcounty', ['0','1','2','3','4','5','6'])
subcounty= st.selectbox('Subcounty', options=[1,2,3,4,5,6], index=1)
#water= st.selectbox('Water', ['1','2','3','4'])
water= st.selectbox('Water', options=[1,2,3,4], index=1)
#sanitation= st.selectbox('Sanitation', ['1','2','3','4'])
sanitation= st.selectbox('Sanitation', options=[1,2,3,4], index=1)
#income= st.selectbox('Income', ['1','2','3','4','5'])
income= st.selectbox('Income', options=[1,2,3,4,5], index=1)
#informal_settlement= st.selectbox('Informal_settlement', ['1','2'])
informal_settlement= st.selectbox('Informal_settlement', options=[1, 2], index=1)

if st.button('Predict'):
    # Prepare input features for prediction
    input_features = np.array([[test_result, sex,age, subcounty, water, sanitation,income,informal_settlement]])  # Ensure this is a 2D array

    # Make prediction
    prediction = model.predict(input_features)
    st.write(f'Predicted Outcome: {prediction[0]:.2f}')
    #st.write(f'Predicted Outcome: {prediction[0]}')
    # Display prediction
    # Assuming the model outputs a probability or a value that needs interpretation for classification
    # For a binary classification model, model.predict_proba might be more appropriate if available.
    # For simplicity, if the model is a regression model trained on binary outcomes,
    # we can interpret the output as a score and potentially threshold it.
    # However, since the goal is predicting probability, a classification model is more suitable.
    # Given the linear regression model, we'll display the predicted value and note it's a score.
    ##st.write(f'Predicted score (interpretation needed for probability): {prediction[0]:.2f}')

2025-08-22 13:17:22.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-22 13:17:22.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-22 13:17:22.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-22 13:17:22.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-22 13:17:22.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-22 13:17:22.408 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-22 13:17:22.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-22 13:17:22.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bar

!npm install -g localtunnel

In [ ]:
!npm install -g localtunnel

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴
added 22 packages in 3s
⠴
⠴3 packages are looking for funding
⠴  run `npm fund` for details
⠴

In [ ]:
!streamlit run /content/cholera_app.py &>/content/cholera_app_logs.txt & # Changed filename

In [ ]:
!npx localtunnel --port 8501

⠙⠹⠸⠼⠴⠦⠧⠇your url is: https://free-berries-go.loca.lt
^C


In [ ]:
import os

# Create the .streamlit directory if it doesn't exist
os.makedirs(os.path.expanduser("~/.streamlit/"), exist_ok=True)

# Write the configuration to config.toml
with open(os.path.expanduser("~/.streamlit/config.toml"), "w") as f:
    f.write("""
    [server]
    enableCORS = false
    """)

print("Streamlit configuration updated successfully!")

Streamlit configuration updated successfully!


In [ ]:
!streamlit run /content/cholera_app.py &>/content/cholera_app_logs.txt & # Changed filename

In [ ]:
!npx localtunnel --port 8501


⠙⠹⠸⠼⠴⠦⠧⠇your url is: https://empty-carrots-march.loca.lt


In [ ]:
!pip install pyngrok


<h3> TASK </h2>

Save the model you created in classfication session and deploy it